apiVersion: batch/v1
kind: CronJob
metadata:
  name: integration-cip-havochvatten
spec:
  schedule: "0 * * * *" # run hourly by default
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            name: integration-cip-havochvatten
            image: ghcr.io/diwise/integration-cip-havochvatten:changeme
            imagePullPolicy: IfNotPresent
            args: ["-nutscodes=$(NUTS_CODES)", "-output=fiware"]
            resources:
              limits:
                cpu: 100m
                memory: 250Mi
              requests:
                cpu: 50m
                memory: 100Mi
          restartPolicy: Never
          serviceAccountName: integration-cip-havochvatten
